language: objective-c
osx_image: xcode7.2
xcode_project: white-fennec.xcodeproj
xcode_scheme: white-fennec

script: 
    xcodebuild -verbose
    -project white-fennec.xcodeproj
    -scheme white-fennec
    -sdk macosx
    clean build test
    -enableCodeCoverage YES
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    | xcpretty -c

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
      on_failure: change
