language: objective-c
notifications:
  email: true
xcode_project: white-fennec.xcodeproj
xcode_scheme: white-fennec
script: xctool -project white-fennec.xcodeproj -scheme white-fennec build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
